# 这些是受支持的赞助模式平台

# GitHub Sponsors
# github: [你的GitHub用户名]

# Buy Me a Coffee
buy_me_a_coffee: suweihongc

# Patreon
# patreon: [你的Patreon用户名]

# 自定义链接 (可以放支付宝/微信赞赏码的图片链接)
# custom: ['https://example.com/donate', 'https://example.com/sponsor-us']
