# 这些是受支持的赞助模式平台

# GitHub Sponsors
github: goldenhawksu

# Buy Me a Coffee
buy_me_a_coffee: suweihongc

# Patreon
# patreon: [你的Patreon用户名]

# 自定义链接 (可以放支付宝/微信赞赏码的图片链接)
custom: https://get.spdt.work/FreeAI_pay.jpg
